theme: jekyll-theme-cayman
title: Agraria - Documentación
description: Documentación técnica y funcional del proyecto Agraria
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
